apiVersion: 1

deleteDatasources:
  - name: gdev-influxdb
  - name: gdev-influxdb-telegraf
  - name: gdev-influxdb2
  - name: gdev-influxdb2-influxql
  - name: gdev-loki-0.3
  - name: gdev-loki-0.4

datasources:
  - name: PostgreSQL
    type: postgres
    url: localhost:5432
    database: homesweethome
    user: postgres
    secureJsonData:
      password: mysecretpassword
    jsonData:
      sslmode: "disable"
